services:
#    sg_platform.example:
#        class: SG\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    sg_platform.antispam:
        class: SG\PlatformBundle\Antispam\SGAntispam
        arguments:
            - "@mailer"
            - locale%
            - 50

    sg_platform.email.application_mailer:
        class: SG\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"
    
    sg_platform.doctrine_listener.application_creation:
        class: SG\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@sg_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }
